name = "gleamblog"
version = "1.0.0"
dependencies = { gleam_stdlib = ">= 0.39.0 and < 1.0.0" , gloml = ">= 0.1.3 and < 1.0.0" , html_lustre_converter = ">= 1.1.0 and < 2.0.0" }
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 


[dev-dependencies]
gleeunit = "~> 1.0"
lustre_ssg = ">= 0.8.0 and < 1.0.0"
lustre = ">= 4.3.2 and < 5.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
lustre_dev_tools = ">= 1.3.4 and < 2.0.0"
